[package]
name = "cortex-m-rtt-panic"
version = "0.1.0"
authors = ["Gerik Kubiak <gerikkub@gmail.com>"]
edition = "2018"

[dependencies.cortex-m-rtt]
path = "../cortex-m-rtt"
version = "0.1.0"

[dependencies.cortex-m]
version = "0.5.6"

[dependencies.cortex-m-rt]
version = "0.5.3"

